---
openapi: 3.0.0
info:
  title: Pi-Hole API
  version: 5.9

servers:
  - url: http://{pihost}/admin/api.php
    variables:
      pihost:
        default: 192.168.1.20
        description: Pi-Hole IP address

paths:
  ?customcname&action=get:
    get:
      tags:
        - dns
      summary: List custom DNS CNAME records
      security:
        - PiHoleAPIToken: []
      operationId: getCustomCNAMERecords
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Data'
  ?customcname&action=add:
    post:
      tags:
        - dns
      summary: Create a custom DNS CNAME record
      security:
        - PiHoleAPIToken: []
      operationId: addCustomCNAMERecord
      requestBody:
        content:
          multipart/form-data:
            schema:
                $ref: '#/components/schemas/CustomCNAMERecord'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomDNSResponse'
  ?customcname&action=delete:
    post:
      tags:
        - dns
      summary: Delete a custom DNS CNAME record
      security:
        - PiHoleAPIToken: []
      operationId: deleteCustomCNAMERecord
      requestBody:
        content:
          multipart/form-data:
            schema:
                $ref: '#/components/schemas/CustomCNAMERecord'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomDNSResponse'

  ?customdns&action=get:
    get:
      tags:
        - dns
      summary: List custom DNS A records
      security:
        - PiHoleAPIToken: []
      operationId: getCustomDNSRecords
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Data'
  ?customdns&action=add:
    post:
      tags:
        - dns
      summary: Create a custom DNS A record
      security:
        - PiHoleAPIToken: []
      operationId: addCustomDNSRecord
      requestBody:
        content:
          multipart/form-data:
            schema:
                $ref: '#/components/schemas/CustomDNSRecord'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomDNSResponse'
  ?customdns&action=delete:
    post:
      tags:
        - dns
      summary: Delete a custom DNS A record
      security:
        - PiHoleAPIToken: []
      operationId: deleteCustomDNSRecord
      requestBody:
        content:
          multipart/form-data:
            schema:
                $ref: '#/components/schemas/CustomDNSRecord'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomDNSResponse'
  ?disable:
    get:
      tags:
        - status
      summary: Disable Pi-Hole server
      security:
        - PiHoleAPIToken: []
      operationId: disableServer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
  ?enable:
    get:
      tags:
        - status
      summary: Enable Pi-Hole server
      security:
        - PiHoleAPIToken: []
      operationId: enableServer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
  ?list={type}:
    get:
      tags:
        - blacklist
        - whitelist
      summary: List blacklisted and whitelisted entries
      security:
        - PiHoleAPIToken: []
      operationId: listEntries
      parameters:
        - in: path
          name: type
          schema:
            type: string
            enum:
              - black
              - regex_black
              - white
              - regex_white
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Data'

  ?status:
    get:
      summary: Get Pi-Hole server status
      tags:
        - status
      operationId: getStatus
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
  ?versions:
    get:
      summary: Get versions of Pi-Hole, FTL, etc.
      tags:
        - status
      operationId: getVersions
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Versions'

components:
  securitySchemes:
    PiHoleAPIToken:
      type: apiKey
      in: query
      name: auth
  schemas:
    CustomCNAMERecord:
      type: object
      properties:
        target:
          type: string
          required: true
          description: Target domain of CNAME record.
        domain:
          type: string
          required: true
          description: DNS name of CNAME record.
    CustomDNSRecord:
      type: object
      properties:
        ip:
          type: string
          required: true
          description: IP address of A record.
        domain:
          type: string
          required: true
          description: DNS name of A record.
    CustomDNSResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
    Data:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
    Status:
      type: object
      properties:
        status:
          type: string
          enum:
            - disabled
            - enabled
    Versions:
      type: object
      properties:
        core_update: 
          type: boolean
        web_update: 
          type: boolean
        FTL_update: 
          type: boolean
        core_current:
          type: string
        web_current:
          type: string
        FTL_current:
          type: string
        core_latest:
          type: string
        web_latest:
          type: string
        FTL_latest:
          type: string
        core_branch:
          type: string
        web_branch:
          type: string
        FTL_branch:
          type: string
